# Generated by Django 4.1.7 on 2023-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone Number')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('profile_pic', models.ImageField(upload_to='accounts/profile_pics', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
