# Generated by Django 4.1.7 on 2023-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('otp_create_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('otp_code', models.CharField(max_length=4)),
            ],
        ),
    ]
