# Generated by Django 4.1.7 on 2023-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
