# Generated by Django 4.1.7 on 2023-03-14 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_client_address_address_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
    ]
