# Generated by Django 4.1.7 on 2023-04-07 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blog_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(default=0, editable=False, related_name='user_blog_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
