# Generated by Django 4.1.7 on 2023-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
