# Generated by Django 4.1.7 on 2023-04-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Message',
        ),
    ]
