# Generated by Django 4.1.7 on 2023-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=255, verbose_name='Banner')),
                ('title', models.CharField(max_length=2550, verbose_name='Title')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('image', models.ImageField(upload_to='about')),
            ],
        ),
    ]
