# Generated by Django 4.1.7 on 2023-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Discount Code')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Percent of Discount')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity of Discount')),
                ('expired', models.BooleanField(default=False, verbose_name='Status of Discount')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
