# Generated by Django 4.1.7 on 2023-03-25 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_price', models.PositiveIntegerField(verbose_name='Total Price')),
                ('address', models.TextField(verbose_name='Address of Client')),
                ('paid', models.BooleanField(default=False, verbose_name='Status of paid')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_of_client', to=settings.AUTH_USER_MODEL, verbose_name='Client Orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='Food Name')),
                ('quantity', models.CharField(max_length=255, verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(verbose_name='Price of One Quantity')),
                ('total_price', models.PositiveIntegerField(verbose_name='Price of Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='orders')),
            ],
        ),
    ]
