# Generated by Django 4.1.7 on 2023-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='menu/foods', verbose_name='Image')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
    ]
